### ISSUE TITLE
suggestion box

### ISSUE THREAD

**Issue by susanchapas** [jjjpanda/me#43]
~- [x] switch background and card colors~
- [x] #47
~- [x] more padding between y-axis and scrollbar; too close to edge of screen~
- [x] #48
~- [x] thinner menu cards~
- [x] #52
- [x] #49
- [x] #50
- [x] #51
~- [x] remove outline on cards on hover; keep glow~

**Comment by jjjpanda** [comment]
- [x] switch background and card colors  - color scheme will be addressed in #49
- [x] more padding between y-axis and scrollbar; too close to edge of screen - addressed by #48
- [x] thinner menu cards - addressed by #48
- [x] remove outline on cards on hover; keep glow - simply denying this because i don't wanna 

the other tasks have been converted to issues, so closing this!
